import './components/_cardHover';
import './components/_portfolioSlider';
import './components/_reviewsSlider';
import './components/_aboutSlider';
// import './components/_canvasAnimation';
import './components/_burger';
import './components/_formValidate';
import './components/_animation';
import './components/_modal';
import './components/_titleAnimation';